ansible_connection: aws_ssm
ansible_aws_ssm_bucket_name: not-so-simple-ecommerce-ansible-ssm-654654554686
terraform_path: /Users/kenerry/Repositories/not-so-simple-ecommerce-iac/terraform
aws_region: us-east-1
aws_access_key: <>
aws_secret_access_key: <>
aws_profile: <>
kube_config: /etc/kubernetes/admin.conf
kube_config_worker: /etc/kubernetes/kubelet.conf